### ISSUE TITLE
Make authentication work with gmail and bitbucket

### ISSUE THREAD

**Issue by gsouf** [phalcon-hosting/phmaster#4]
You will have to think to check what is common between github, google and bitbucket oauth and put all this common stuff into : https://github.com/Phalcon-hosting/phmaster/blob/develop/app/library/PH/Master/Auth/OAuth/OAuth2.php

**Comment by gsouf** [comment]
You will also have to think to update the structure of the db
For instance we have to know if it is an account from google, github, or something else..

**Comment by thecodeassassin** [comment]
What is the status on this?
